### ISSUE TITLE
"No applicable update data found" (EU PS3 4.90)

### ISSUE THREAD

**Issue by niansa** [ZHassanQ/PS3-Guide#1]
Hi!

I am attempting to run this guide on an EU PS3 super slim 4.90, however I keep getting that error message both in system and recovery. The thumb drive is definitely formatted correctly.

Thanks in advance
Tuxifan

**Comment by ZHassanQ** [comment]
> Hi!
> 
> 
> 
> I am attempting to run this guide on an EU PS3 super slim 4.90, however I keep getting that error message both in system and recovery. The thumb drive is definitely formatted correctly.
> 
> 
> 
> Thanks in advance
> 
> Tuxifan

Hi, 

When does this happens?

**Comment by niansa** [comment]
Right after starting "update from storage"

**Comment by ZHassanQ** [comment]
> Right after starting "update from storage"

Did you check the md5 (integrity) of the file? Your download maybe was corrupted.

- If it was HFW it works in all models.

- CFW only works in specific models.

**Comment by niansa** [comment]
Yes, I have verified the md5 after downloading and after flashing to the thumb drive and replugging it. It's HFW.

**Comment by niansa** [comment]
Clarification, it's a PS3 Super Slim.

**Comment by Xem0n** [comment]
I've got the same issue

**Comment by ZHassanQ** [comment]
Did you resolve the issue? I think it's a usb port issue, and/or try inserting it to the usb port that's closest to the Disc reader.

**Comment by Xem0n** [comment]
> Did you resolve the issue? I think it's a usb port issue, and/or try inserting it to the usb port that's the most right.

USB was inserted to the most right port but still didn't work. Trying another USB helped.

**Comment by niansa** [comment]
I tried another USB port and unplugging the controller. Neither helped.

**Comment by ZHassanQ** [comment]
Try doing all these steps:

1. Format your Flash Drive to FAT32 and MBR.
2. Use the most right port
3. Try in recovery mode
4. Don’t plug in any other device while it’s installing.
- You can do this by pressing X to start then immediately unplug your controller.

**Comment by niansa** [comment]
Okay, gave it a try. It installed but then failed midway through.
It's now stuck in a loop where it attempts to reinstall it whenever I turn the PS3 on, in both recovery and normal mode.

**Comment by ZHassanQ** [comment]
Did you try the other port as well?

**Comment by niansa** [comment]
Yeah, ofc.

**Comment by ZHassanQ** [comment]
4.91 released, update your PS3 normally (You can with an internet connection) then follow the guide again. Hopefully your issue will be resolved.

**Comment by niansa** [comment]
It keeps going back to wanting to reinstall the current update without an option to stop and download a new one.

**Comment by ZHassanQ** [comment]
1. [Download OFW 4.91 from PlayStation website](http://dus01.ps3.update.playstation.net/update/ps3/image/us/2024_0227_3694eb3fb8d9915c112e6ab41a60c69f/PS3UPDAT.PUP)
2. Format your Flash Drive correctly (FAT32 and MBR)

3. Follow [this page](https://github.com/ZHassanQ/PS3-Guide/wiki/3.HEN-Installing-Hybrid-Firmware) as if you're installing HFW, and then after installing 4.91 OFW,. Do it again but with HFW 4.91

**Comment by niansa** [comment]
> Now that you’re on safe mode, choose the sixth option and update your PS3.

I never get any options here though, it just goes right to attempting to reinstall the failed update.

**Comment by ZHassanQ** [comment]
Are you sure your PS3 is not in anyway has a broken or faulty components? Try asking [here,](https://www.reddit.com/r/ps3homebrew/?) but mention that you did all the above so you don’t have the same repeated answer.
